### ISSUE TITLE
panorama camera support 

### ISSUE THREAD

**Issue by bring728** [andyyankai/psdr-jit#10]
Hi, thank you for sharing your wonderful project.

Currently I am having trouble rendering panorama image with psdr-jit.

Do you have any plans to support panorama camera? If not, could you give me some advice?

**Comment by andyyankai** [comment]
No, you can try to add a new camera type similar to [perspective.h](https://github.com/andyyankai/psdr-jit/blob/main/include/psdr/sensor/perspective.h) and [orthographic.h](https://github.com/andyyankai/psdr-jit/blob/main/include/psdr/sensor/orthographic.h)

**Comment by bring728** [comment]
thank you! i will try.
