### ISSUE TITLE
point light source

### ISSUE THREAD

**Issue by bring728** [andyyankai/psdr-jit#11]
Hello. Does this library not support other light sources like point lights in addition to area lights and environment maps?

**Comment by GuangyanCai** [comment]
Sorry for the late reply. Our renderer is based on the paper [Path-Space Differentiable Rendering](https://dl.acm.org/doi/abs/10.1145/3386569.3392383) and in the original paper, it assumes that there are no zero-measure light sources, such as point lights. While it is not impossible to relax the assumption, it requires significant changes to our system. We usually just approximate the point light with a very small area light. 

@andyyankai Do you have anything additional comments?

**Comment by andyyankai** [comment]
You can check [collocated](https://github.com/andyyankai/psdr-jit/blob/main/src/integrator/collocated.cpp) integrator
which kind of similar to a point light.
