### ISSUE TITLE
What is the simplified version of Mitsuba’s XML exactly?

### ISSUE THREAD

**Issue by HospitableHost** [andyyankai/psdr-jit#6]
I want to use your differentiable renderer to render a scene from 3D-FRONT. So I have to transfer the json of a scene in 3D-FRONT to the xml file the renderer used. And in the PSDR-CUDA official documentation, it wrote "PSDR-CUDA renders virtual scenes described using a simplified version of Mitsuba’s XML”, it's too simple to guide me to render a scene. So have you rendered 3D-FRONT before? Or what is the simplified version of Mitsuba’s XML exactly? Thanks so much for your help!

**Comment by andyyankai** [comment]
You can check some xml file here: https://github.com/andyyankai/psdr-jit/tree/psdr_room/unit_test
These are some test I used long ago but might be helpful.
bascially if a xml works for mitsuba it should also works for psdr-jit (although it won't have all the features)

**Comment by HospitableHost** [comment]
Thanks for your response. I saw that you used bsdf type="microfacet" in your example. But I didn’t find the definition of such bsdf type in mitsuba’s documentation. Is this unique for your PSDR-CUDA?

**Comment by andyyankai** [comment]
psdr-jit has microfacet bsdf, which is unique

**Comment by hfzi** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
yrjyrj123, @jobot0, @loureirorg, @danhnn, @chengang21, @physician, @tyao1, @JoukoSalonen, @XuyangSong, @nickname1234567891, @phreic, @larryliuqing, @ashwin9999, @TaiPhamD, @zs9024, @sooham, @dut3062796s, @jasquibb, @m-bo-one, @ZGQ-inc, @kenjichanhkg, @lfzm, @techping, @shalakhin, @RutZap, @kravenoff42, @jkariscodes, @nanbeiwei2014, @youcanya, @hyperji, @naftalimurgor, @vytk, @beastybryan, @edydkim, @RogerGold, @chimerin, @Kampoz18, @oeohomos, @EdwinCheruiyot, @sykwer, @thomasklemm, @jslauthor, @lonchak23, @cinquemb, @songwentong, @dsky1990, @VGCif, @DeflatedPickle, @xiaofei6677, @orhanalparslanyosefl20, @drizzyrdrgz-exe, @HaochenLiu, @bengartner, @phanil, @Katastrophos, @beckhamaaa, @wanglg007, @abduld, @cdave1, @wenyanca, @tranvictor, @arthurhenrique, @mattxlee, @danielsz, @NorikDavtian, @takumitx, @cfiumara, @biafra23, @ZECTBynmo, @3tinkers, @lcmftianci, @ujweng, @FOWind, @skropf, @cNoveron, @dajunx, @Vic020, @cupidhack, @stevenchen3, @vis7, @dennisthadathil, @efremidze, @bakugo, @cpplover, @zk1056782358, @imxiaohui, @y-c, @phivh, @PeiTheFarmer, @kaseasaraankasea, @kankajm, @juanmaneo, @kjunu, @georgek146, @mrbaron, @LittleClose, @minkj1992, @yunh-kwak, @cleanunicorn
