### ISSUE TITLE
How to remove a mesh from psdr.Scene?

### ISSUE THREAD

**Issue by qijiyaolinZGH** [andyyankai/psdr-jit#7]
I only found the function for adding meshes in the example code. Is there a method to remove meshes?

**Comment by andyyankai** [comment]
No (it don’t make sense for diff renderer to have this feature)

You will need to construct a new scene for that.

**Comment by qijiyaolinZGH** [comment]
If I want to keep an object's position unchanged but change its orientation, how should I do it?
