### ISSUE TITLE
gcc version for compiling

### ISSUE THREAD

**Issue by dongchen-yang** [andyyankai/psdr-jit#9]
Hi, thanks for your great work. I was trying to use pip to install your package but this error message occurs:

" /tmp/pip-install-jlubddp9/psdr-jit_f556b7a3086348cea25235b951be4e52/ext/drjit/ext/drjit-core/src/common.h:91:53: error: 'uint8_t' does not name a type
         91 | template <> struct uint_with_size<1> { using type = uint8_t; };"

I think this might be an issue with the gcc version. Could you give me some further instruction on how to fix it? Thanks in advance.

**Comment by andyyankai** [comment]
I haven't built with GCC for a long time. I think I was using GCC-11 before. Also, Wenzel mentioned that DrJit has not been intended to support GCC for the past few years, so they only test it on Clang.

I also suggest you build the system on Windows, which is much easier. I have never seen anyone have too much trouble building it on Windows so far.

**Comment by dongchen-yang** [comment]
Thanks for your reply. I tried to build the system on Windows but it seems like having some trouble finding gcc and g++, do you know how to fix it?
![image](https://github.com/andyyankai/psdr-jit/assets/48226450/fb55528c-f7c4-4dfd-9c10-f63994bf0b10)


I tried the solution mentioned [here](https://stackoverflow.com/questions/70524164/cmake-c-compiler-not-set-after-enablelanguage) by manually adding the path to the CMakeList.txt but it is not working.

**Comment by dongchen-yang** [comment]
still not sure what is going on but finally fixed it by installing on wsl ^ ^
